"""empty message

Revision ID: 1733abe24b15
Revises: 
Create Date: 2025-02-20 22:49:05.235492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1733abe24b15'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_info',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_url'),
    sa.UniqueConstraint('title')
    )
    op.create_table('promocod_info',
    sa.Column('promocode', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('promocode')
    )
    op.create_table('users_by_product',
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('by_product_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('card_title', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('promocode', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['card_title'], ['card_info.title'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('promocode')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_by_product')
    op.drop_table('promocod_info')
    op.drop_table('card_info')
    # ### end Alembic commands ###
